#!/bin/bash

# Get the current script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Open all the issues in a browser
(cd $SCRIPT_DIR/..; ditz html | awk '{ print $4}' | xargs $BROWSER)
