#!/usr/bin/env perl

use common::sense;

use Cwd 'abs_path';
use Dir::Self;
use File::Basename;

if (not -f 'OMakeroot') {
   open my $fh, '>', 'OMakeroot'
      or die "Could not create OMakeroot: $!";
   say $fh "open rules/default";
}
if (not -f '.cvsignore') {
   open my $fh, '>', '.cvsignore'
      or die "Could not create .cvsignore: $!";
   say $fh "_build";
   say $fh "_install";
}

my ($STDLIB) = `omake --version` =~ /Default library directory : (.+)/;

my $rootdir = abs_path (dirname __DIR__);
$ENV{OMAKEPATH} = "$STDLIB:$rootdir";

exec "omake", "--no-S", "rootdir=$rootdir", "projdir=.", @ARGV;
