#!/usr/bin/env perl

use strict;
use warnings FATAL => 'all';

use Cwd 'abs_path';

die "No projects given on command line\n" unless @ARGV;

# $(rootdir)
my ($OBUILD) = abs_path $0 =~ m|(.+)/script/[^/]+$|;

die "cannot determine obuild base directory\n" unless $OBUILD;

# Clear obuild's submodule directories.
for (glob "$OBUILD/src/*") {
   next if /OMakefile/; # don't delete the meta-OMakefile
   system "rm -rf $_";
}

my %ignore = map { $_ => undef } (
   '.',
   '..',
   '.git',
   'debian',
   'obuild',
);

# Link projects we want to build to the source path.
for my $dir (@ARGV) {
   my $THIS = abs_path $dir;
   $THIS = `basename $THIS` or die;
   chomp $THIS;

   my $DIR = "$OBUILD/src/$THIS";
   die "project '$THIS' already exists\n" if -e $DIR;
   mkdir $DIR or die "cannot mkdir '$DIR': $!";

   opendir my $dh, $dir or die "cannot opendir '$dir': $!";
   for (sort readdir $dh) {
      next if exists $ignore{$_};
      system "cp", "-a", "$dir/$_", "$DIR/$_";
   }
}
