#!/bin/sh

set -ex

for pkg in "$@"; do
   cd ..
   git clone --depth=1 https://github.com/pippijn/$pkg
   cd $pkg
   sudo mk-build-deps -ir
   dpkg-buildpackage -b -us -uc
   sudo dpkg -i ../*.deb || sudo apt-get -f install
   rm ../*.deb
done
